### ISSUE TITLE
🐞 Engine stop is not called when the pipeline fails

### ISSUE THREAD

**Issue by sagikazarmark** [dagger/dagger-for-github#110]
### What is the issue?

When the Dagger command fails for any reason, engine stop is not called.

The GitHub snippet in the documentation has an added condition to make sure engine stop runs even if the command before it fails:

```yaml
      - name: Stop Engine
        run: docker stop -t 300 $(docker ps --filter name="dagger-engine-*" -q)
        if: always()
```

### Dagger version

dagger v0.9.7 (registry.dagger.io/engine) darwin/arm64
