### ISSUE TITLE
✨ Allow exporting engine logs

### ISSUE THREAD

**Issue by sagikazarmark** [dagger/dagger-for-github#130]
### What are you trying to do?

I'm trying to debug dagger/dagger#7593, but there is no way in the action to export engine logs.

### Why is this important to you?

Figure out why Dagger is slow.

### How are you currently working around this?

I'm using this snippet:

```
      - name: Export Dagger Engine logs
        run: docker logs $(docker container list --all --filter 'name=^dagger-engine-*' --format '{{.Names}}') > engine.log
        if: always()

      - name: Upload Dagger Engine logs as artifact
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        if: always()
        with:
          name: "Dagger Engine logs"
          path: engine.log
          retention-days: 14
```

But the engine log comes back basically empty, because the action is terminated due to a timeout.
