### ISSUE TITLE
✨ Get version from dagger.json

### ISSUE THREAD

**Issue by jsok** [dagger/dagger-for-github#138]
### What are you trying to do?

In order to keep the Dagger version used in GitHub Actions the same as the engine version used, it would be nice to be able to supply a path to a `dagger.json` file and have the engine version parsed from it and used.

This behaviour would be similar to the `setup-go` action which can get the Go version from a `go.mod` file: https://github.com/actions/setup-go?tab=readme-ov-file#getting-go-version-from-the-gomod-file.

## Example

```yaml
uses: dagger/dagger-for-github@v5
with:
  verb: call
  args: something
  version-file: path/to/dagger.json
```

### Why is this important to you?

This will simplify the process of upgrading Dagger.

### How are you currently working around this?

Updating Dagger requires updating the version number in multiple places (dagger.json and every GitHub workflow YAML file which uses this action).
