### ISSUE TITLE
🐞 Error running module with multiline output

### ISSUE THREAD

**Issue by opopops** [dagger/dagger-for-github#161]
### What is the issue?

Since the latest versions (v6.15.0 and v7.0.0), I encounter an error when running a module that returns a multi-line string.

### Dagger version

dagger v0.14.0

### Steps to reproduce

Here is my GitHub action step that is failing:

```yaml
steps:
      - name: Lint
        uses: dagger/dagger-for-github@v7
        with:
          version: 0.14.0
          module: github.com/opopops/daggerverse/helm@main
          verb: call
          args: |
            lint \
              --path chart \
              --strict \
```

### Log output

<img width="748" alt="Screenshot 2024-11-10 at 11 57 44" src="https://github.com/user-attachments/assets/585f9605-bb76-44a4-b261-083ad8fa1255">

**Comment by spargonaut** [comment]
I'm running into the same issue.

### Dagger Version(s)
0.14.0 and 0.13.7. (I've tried both versions with the same result)

### Here's my github action step
``` yaml
      - name: Build, Test, and Package the artifact
        uses: dagger/dagger-for-github@v6
        with:
          version: "0.13.7"
          verb: call
          args: verify-build --source=. --db-init-file=./zDB/init.sql
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
```

### Log Output
```
Full trace at https://dagger.cloud/spargonaut/traces/<redacted>
{
    "_type": "Container",
    "defaultArgs": [],
    "entrypoint": [
        "java",
        "-jar",
        "/app/FarmstandTracker.jar"
    ],
    "mounts": [],
    "platform": "linux/amd64",
    "user": "",
    "workdir": "/"
}
A new release of dagger is available: v0.13.7 → v0.14.0
To upgrade, see https://docs.dagger.io/install
https://github.com/dagger/dagger/releases/tag/v0.14.0
Error: Unable to process file command 'output' successfully.
Error: Invalid format '    "_type": "Container",'
```

Happy to provide more info upon request.
