### ISSUE TITLE
Add cache option to Dagger action

### ISSUE THREAD

**Issue by TomChv** [dagger/dagger-for-github#39]
When https://github.com/dagger/dagger/pull/1839 will be merged, we should update this action to supports cache option.

In a discussion with @aluzzardi, we talk about the following shape: 

```yaml
        name: Dagger
        uses: dagger/dagger-for-github@v2
        with:
          cache: true // New option
          cache-scope: example // Scope of the cache
          args: do test
```

That would add 

- `cache`: enable or disable GitHub cache for dagger | set to `false` by default?
- `cache-scope`: explicit cache scope, useful to do not override existing cache from other action | set to `dagger` by default?

**Question**
Should we also add `mode` option?

**Useful links**
- [Buildkit GitHub cache](https://github.com/moby/buildkit#github-actions-cache-experimental)
