### ISSUE TITLE
dagger-for-github@v3 is not working.

### ISSUE THREAD

**Issue by knaou** [dagger/dagger-for-github#86]
### What is the issue?

dagger-for-github@v3, which was working until yesterday, has stopped working today.

Details:

I used dagger-for-github@v3.
The files downloaded in Action had changed.
when it was working until yesterday: https://dl.dagger.io/dagger/releases/0.2.36/dagger_v0.2.36_linux_amd64.tar.gz
when it failed today: https://dl.dagger.io/dagger/releases/0.3.12/dagger_v0.3.12_linux_amd64.tar.gz

For dagger-for-github@v3, the correct move appears to be to download the 0.2 series, and for dagger-for-github@v4 series, download the 0.3 series.
By the way, if I specify dagger-for-github@v4 in GitHub Action, I got an error saying it doesn't exist, so I'm guessing that you probably got the release wrong somehow.

### Log output
```
project init
  /opt/hostedtoolcache/dagger/0.3.12/x64/dagger project init
  Error: unknown command "project" for "dagger"
  Run 'dagger --help' for usage.
```

### Steps to reproduce

Execute github action with follow job.

```
jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    services:
      ...
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare dagger and test environment
        uses: dagger/dagger-for-github@v3
        with:
          cmds: |
            project init
```

### SDK version

-

### OS version

-
